version: '3'
services:
  app:
    image: mattarnster/releasetrackr:1.1
    env_file: .env
    links:
      - mongo
    ports:
      - "127.0.0.1:3000:3000"
    restart: always
  
  mongo:
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
    volumes:
      - "/root/releasetrackr/dbdata:/data/db"
    ports:
      - "127.0.0.1:27017:27017"
    restart: always